### ISSUE TITLE
Error com.azure.android.communication.ui.calling.presentation.fragment.calling.lobby.ConnectingLobbyOverlayViewModel

### ISSUE THREAD

**Issue by guilhermeheibel** [Azure-Samples/communication-services-ui-library-maui#28]
I'm getting the following error when I open a call, it happens constantly, however in some scenarios it manages to close the call correctly, would anyone have any insight into the problem?

-- End of managed Java.Lang.Throwable stack trace ---
java.lang.Throwable
	at com.azure.android.communication.ui.calling.presentation.fragment.calling.lobby.ConnectingLobbyOverlayViewModel.handleMicrophoneAccessFailed(ConnectingLobbyOverlayViewModel.kt:95)
	at com.azure.android.communication.ui.calling.presentation.fragment.calling.lobby.ConnectingLobbyOverlayView.start(ConnectingLobbyOverlayView.kt:53)
	at com.azure.android.communication.ui.calling.presentation.fragment.calling.CallingFragment.onViewCreated(CallingFragment.kt:107)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3148)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:600)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2103)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1998)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1941)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:661)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by iaulakh** [comment]
Hi @guilhermeheibel,

Thank you for trying the MAUI sample. Could you please share the following information:
1. Which version of the UI Library are you using?
2. Are microphone permissions granted to the app? The UI Library will request permissions on launch.
3. What is the device's Android API version?

**Comment by Mohtasim** [comment]
Closing the issue due to no update. Please feel free to open a new issue if facing the same problem with the queried information here.
Thanks :)
